version : 2
jobs:
  build_one:
    docker: 
      - image: circleci/ruby:2.4.1
    steps: 
      - checkout
      - run: echo "A first hello"
  build_two:
    docker: 
      - image: circleci/ruby:2.4.1
    steps: 
      - checkout
      - run: echo "A Double hello"
  workflows: 
    version: 2
    build_one_two:
      jobs:
        - build_one
        - build_two